### ISSUE TITLE
define a thread

### ISSUE THREAD

**Issue by nichoth** [ssbc/ssb-threads#12]
This is an issue to request a definition of an ssb thread. A thread is distinct from a feed. Does it depend on the text content in a message?

**Comment by staltz** [comment]
It should be this, no? 

https://github.com/ssbc/ssb-threads#thread-objects

> Any message that has its `root` field or `branch` field or `fork` field pointing to the root of the thread can be included in this array

**Comment by nichoth** [comment]
ok, so any message that has a `root` field pointing at the key of the root message is in a thread. as an example, is that set within the `content` section of a message? or is it in the `value` section?

```js
{    
     key: 'abc',
     value: {
         // ...
         content: {
            type: 'post',
            root: 'some-key',
            text: 'woooo',
            mentions: ['my-hash']
        },
     }
}
```

**Comment by nichoth** [comment]
Also, I noticed that if i call `threads` with a message ID and there are no threaded messages (it's just a single message, no messages referencing it), then it returns `null`. I expected it to return the single message with `id` though. Is this expected?

```js
            sbot.threads.thread({
                root: id,
                allowlist: ['test'],
                reverse: true, // threads sorted from most recent to least recent
                threadMaxSize: 3, // at most 3 messages in each thread
            }),
```

**Comment by nichoth** [comment]
I've learned it is valid in the `content` section

**Comment by staltz** [comment]
Yes, everything outside of `content` is part of the SSB spec and does not change with message types. In other words, the only creative freedom we have is all inside of `content`
