### ISSUE TITLE
Can you get a thread given a child key?

### ISSUE THREAD

**Issue by nichoth** [ssbc/ssb-threads#13]
If you have a the key `%b`, and `%b` is a response to `%a` is it possible to get the thread that is `%b -> %a`? 

I see there is a method `ssb.threads.thread(opts)`, where you can pass in an option `root`, but is it possible to pass in a key from any message in the thread, and get the resulting thread?

```js
    {
        "key": "%b",
        "value": {
          // ...
          "content": {
            "type": "test",
            "text": "woooo 2",
            "root": "%a"
          }
      }
```

```js
     {
        "key": "%a",
        "value": {
          // ...
          "content": {
            "type": "test",
            "text": "woooo 1"
          }
      }
```

**Comment by staltz** [comment]
I don't understand the question, what is the "thread `%b -> %a`"? Or do you want to get the message `a` given the key `%a`?

**Comment by nichoth** [comment]
We want to get an array, as in the response from `ssb.threads.thread(opts)`. It returns a 'thread object of messages'.

So if you have
```js
            sbot.threads.thread({
                root: id,
                allowlist: ['test'],
                reverse: true, // threads sorted from most recent to least recent
                threadMaxSize: 3, // at most 3 messages in each thread
            }),
            S.collect((err, [thread]) => {
            })
```

it should give you `thread.messages` equal to `[%a, %b]`. (an array of all messages in the thread)

**Comment by staltz** [comment]
So, given a message key `%b` you want to get the thread `[a, b]`?

Assuming the above is what you meant, you would first have to fetch `b` from `%b` using sbot.db.get and then once you have `b` you can look up its root field, find `%a`, then use sbot.threads.thread

**Comment by nichoth** [comment]
ok thanks @staltz . That's more or less what I had thought to do as well
