### ISSUE TITLE
Need a bit more documentation on what "reverse" does

### ISSUE THREAD

**Issue by KyleMaas** [ssbc/ssb-threads#7]
The first example has:

`reverse: true, // threads sorted from most recent to least recent`

But that seems to be the only documentation of it.  It would be nice if all of the:

`opts.reverse: boolean`

...below it were documented like the other parameters.

**Comment by staltz** [comment]
Thanks. I did it in the db2 branch

**Comment by KyleMaas** [comment]
Much improved.  Thank you!
