### ISSUE TITLE
Need more documentation on what "public" vs "publicSummary" do

### ISSUE THREAD

**Issue by KyleMaas** [ssbc/ssb-threads#8]
I figured it out by trying them both, but it'd be nice if it said what they did.

**Comment by staltz** [comment]
I would appreciate more accurate feedback. Currently the README describes what "thread objects" are and what "summary objects" are, and then says that `ssb.threads.public` delivers thread objects and `ssb.threads.publicSummary` delivers summary objects.

**Comment by KyleMaas** [comment]
Hm.  Looking at it with that perspective, I see what you're saying.  As for more clear feedback, the way I read it I didn't realize that the thread objects vs. summary objects the function documentation referred to meant that they were defined above.  Mentally, I read through the format and function sections and categorized those as two different disconnected things and thought, by the time I reached the functions, that they were referring to more of a generic undocumented format relating to threads vs. a generic undocumented format relating to summaries.

It would help if those terms in the function documentation were quoted/capitalized the same as the ones above.  Or said "(see above for format)".  Or even better if they were both capitalized the same and had intrapage topic links, it would help clarify that.  For an easy explanation of how to do this, see:

https://stackoverflow.com/a/45508928

Just anything to solidify the context when reading about a function without having to have a mental backreference to a subtopic.
